### ISSUE TITLE
Nested keys issue

### ISSUE THREAD

**Issue by jsirex** [vmchale/tomlcheck#1]
Example from https://github.com/toml-lang/toml
```
○ cat test.toml
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
○ tomlcheck -f test.toml
test.toml:2:9:
  |
2 | physical.color = "orange"
  |         ^
unexpected '.'
expecting '=' or alphanumeric character
```

**Comment by das-g** [comment]
Also occurs within tables. Another example [from the TOML 0.5.0 spec](https://github.com/toml-lang/toml/blob/v0.5.0/versions/en/toml-v0.5.0.md#inline-table):

```toml
[name]
first = "Tom"
last = "Preston-Werner"

[point]
x = 1
y = 2

[animal]
type.name = "pug"
```

output
```
example.toml:10:5:
   |
10 | type.name = "pug"
   |     ^
unexpected '.'
expecting '=' or alphanumeric character

```
